"""A warm claude container's mcp.json (unlike codex's config.toml) never got
`_strip_unstable_warm_headers`-style filtering (card
3d65bf3b-9510-81b0-8b50-d8f3b74f4374, "Gap 2"). Its --mcp-config file is
written once — on the cold path, or on warm-container CREATION — and never
regenerated by dispatch_turn() on later turns, so whatever
X-Aw-Caller-Run-Id/X-Aw-Context-* headers agents-platform-multitenant sent
for THAT turn froze there for the container's whole (up to 6h) life.

That alone would just mean a stale value — annoying, but survivable if
nothing else compensated. What makes it a hard failure: aw-backend's
gateway.py only falls back to its live, Redis-backed `_resolve_warm_context`
(keyed on the STABLE X-Aw-Warm-Token, refreshed on every turn by
agents-platform-multitenant's `set_warm_token_run`) when the header-derived
value is ABSENT (`if not caller_run_id`, `if "NOTION_TASK_ID" not in
context`). A stale header is present, so it always wins over the fresh
Redis value — the aw_kanban page_id auto-fill silently uses turn 1's card
(or none) for every later turn.

Live-confirmed by the Debugger (run f0afe079a2d54f638457bfc9fd8cfb71): the
container's own OS env showed the correct NOTION_TASK_ID, yet
`get_kanban_card()` with no page_id still failed "page_id is required" —
proof the header path is broken independent of (and in addition to) the OS
env staleness fixed separately in warm_pool.dispatch_turn's claude branch.

Fix: strip the same per-turn-changing header set from claude's mcp.json that
codex's `_render_codex_config_toml` already stripped for its config.toml —
generalized here to also catch X-Aw-Context-* (codex's own
`_CODEX_UNSTABLE_HEADERS` only ever matched the two literal
X-Aw-Warm-Token/X-Aw-Caller-Run-Id names, missing X-Aw-Context-* despite the
comment above it naming that as unstable too — so this fix also closes that
gap for codex, not just claude).

Run: python3 -m pytest tests/test_warm_mcp_context_headers_stripped.py
"""
from __future__ import annotations

import json
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from agents_platform_runners_app import execute as execute_mod  # noqa: E402

SHARED_CODEX_CONFIG_TOML = (
    '[projects."/opt/aw-workspace"]\n'
    'trust_level = "trusted"\n'
)

#: What agents-platform-multitenant's executor.py::_build_runner_extra_headers
#: ships over the wire on every single dispatch — the stable X-Aw-Warm-Token
#: alongside the per-turn X-Aw-Caller-Run-Id and (when this run has a card)
#: X-Aw-Context-Notion-Task-Id.
SERVERS_WITH_CONTEXT = {
    "aw-gateway": {
        "type": "streamable-http",
        "url": "http://aw-app-mcp-gateway:9200/mcp",
        "headers": {
            "Authorization": "Bearer live-gateway-token",
            "X-Aw-Caller-Run-Id": "run-turn-1",
            "X-Aw-Warm-Token": "warm-token-abc123",
            "X-Aw-Context-Notion-Task-Id": "task-from-turn-1",
        },
    }
}


# ---------------------------------------------------------------------------
# _strip_stale_identity_headers — the shared helper both CLIs now route through
# ---------------------------------------------------------------------------

def test_strips_caller_run_id_and_any_context_header_but_keeps_warm_token():
    """X-Aw-Warm-Token is deliberately NOT stripped by the shared helper —
    it's the stable key gateway.py's Redis fallback is resolved BY, so
    claude (no env-var indirection like codex's) needs it left in place."""
    headers = execute_mod._strip_stale_identity_headers({
        "Authorization": "Bearer x",
        "X-Aw-Caller-Run-Id": "run-1",
        "X-Aw-Warm-Token": "tok",
        "X-Aw-Context-Notion-Task-Id": "task-1",
        "X-Aw-Context-Source-Device": "telegram",
    })

    assert headers == {"Authorization": "Bearer x", "X-Aw-Warm-Token": "tok"}


def test_none_and_empty_are_safe():
    assert execute_mod._strip_stale_identity_headers(None) == {}
    assert execute_mod._strip_stale_identity_headers({}) == {}


# ---------------------------------------------------------------------------
# codex's _render_codex_config_toml — same fix, closes the X-Aw-Context-*
# gap the old literal-name-only filter missed
# ---------------------------------------------------------------------------

def test_codex_config_toml_also_drops_context_headers():
    cfg = tomllib.loads(
        execute_mod._render_codex_config_toml(SHARED_CODEX_CONFIG_TOML, SERVERS_WITH_CONTEXT))
    server = cfg["mcp_servers"]["aw-gateway"]

    assert server["http_headers"]["Authorization"] == "Bearer live-gateway-token"
    assert "X-Aw-Caller-Run-Id" not in server["http_headers"]
    assert "X-Aw-Warm-Token" not in server["http_headers"]
    assert "X-Aw-Context-Notion-Task-Id" not in server["http_headers"]
    assert "task-from-turn-1" not in execute_mod._render_codex_config_toml(
        SHARED_CODEX_CONFIG_TOML, SERVERS_WITH_CONTEXT)


# ---------------------------------------------------------------------------
# claude's mcp.json, via _build_container_kwargs — the actual Gap 2 fix
# ---------------------------------------------------------------------------

BASE_JOB = {
    "run_id": "run-turn-1", "cli": "claude", "agent_id": "agent-1", "prompt": "hi",
    "mcp_servers": SERVERS_WITH_CONTEXT,
}


def _write_claude_mcp_json(tmp_path, monkeypatch) -> dict:
    home = tmp_path / "home"  # deliberately empty — no .claude dir, so
    home.mkdir()               # direct_home_mount stays False and the mcp.json
    monkeypatch.setattr(execute_mod, "REAL_HOME", str(home))
    monkeypatch.setattr(execute_mod, "WORKSPACE_HOME_HOST_DIR", "")
    monkeypatch.setattr(execute_mod, "WORKSPACE_HOST_DIR", "/host/aw-workspace")
    monkeypatch.setattr(execute_mod, "WORKSPACE_CONTAINER_DIR", str(tmp_path / "ws"))

    execute_mod._build_container_kwargs(BASE_JOB)

    mcp_path = tmp_path / "ws" / ".claude" / "isolated" / "run-turn-1" / "mcp.json"
    return json.loads(mcp_path.read_text())


def test_claude_mcp_json_drops_stale_caller_run_id_and_context_headers(tmp_path, monkeypatch):
    doc = _write_claude_mcp_json(tmp_path, monkeypatch)
    headers = doc["mcpServers"]["aw-gateway"]["headers"]

    assert headers["Authorization"] == "Bearer live-gateway-token"
    assert "X-Aw-Caller-Run-Id" not in headers
    assert "X-Aw-Context-Notion-Task-Id" not in headers


def test_claude_mcp_json_keeps_the_stable_warm_token(tmp_path, monkeypatch):
    """X-Aw-Warm-Token must survive — it's what lets the gateway's Redis
    fallback (_resolve_warm_context) identify this container at all once the
    unstable headers are gone."""
    doc = _write_claude_mcp_json(tmp_path, monkeypatch)
    headers = doc["mcpServers"]["aw-gateway"]["headers"]

    assert headers["X-Aw-Warm-Token"] == "warm-token-abc123"
