"""A warm claude container's mcp.json (unlike codex's config.toml) never got
`_strip_unstable_warm_headers`-style filtering (card
3d65bf3b-9510-81b0-8b50-d8f3b74f4374, "Gap 2"). Its --mcp-config file is
written once — on the cold path, or on warm-container CREATION — and never
regenerated by dispatch_turn() on later turns, so whatever
X-Aw-Caller-Run-Id/X-Aw-Context-* headers agents-platform-multitenant sent
for THAT turn froze there for the container's whole (up to 6h) life.

The original fix here (2026-09-09) stripped BOTH header families, reasoning
from "aw-backend's gateway.py::_resolve_warm_context" — a different, unrelated
legacy MCP gateway (see aw-mcp-gateway's own caller_context.py module
docstring, which names it as the thing it "ports the same logic" from, not
the same file) whose Redis fallback only ever fires when the header-derived
value is ABSENT, so a stale frozen header there permanently wins over a
fresh Redis resolution.

Corrected 2026-09-19 (card fix-schedule-wakeup-caller-run-id): THIS
deployment's actual gateway (apps/mcp-gateway/back/gateway/
caller_context.py::capture()) has the opposite precedence — a resolved
X-Aw-Warm-Token always OVERWRITES the header value, and the header is used
only as a fallback when resolution fails (no warm_redis_url configured,
unmapped token, or Redis down). Under that precedence, stripping
X-Aw-Caller-Run-Id never helps (a successful resolution replaces it anyway)
and is actively harmful when Redis isn't configured: instead of degrading to
turn-1's frozen-but-present identity, the container has NO identity at all,
and every identity-gated tool (schedule_wakeup, ask_human, mark_flow_done,
...) hard-400s "Could not identify this run" for the whole life of the
container. Live-confirmed on a workspace with no warm_redis_url set on the
mcp-gateway app.

X-Aw-Context-* stays stripped: aw-mcp-gateway never forwards it to any
upstream (it isn't in caller_context.FORWARDED) and nothing resolves it from
Redis, so unlike the caller-run-id header there is no fallback value to lose
by dropping it — it is simply dead weight in a frozen config either way.

Run: python3 -m pytest tests/test_warm_mcp_context_headers_stripped.py
"""
from __future__ import annotations

import json
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from agents_platform_runners_app import execute as execute_mod  # noqa: E402

SHARED_CODEX_CONFIG_TOML = (
    '[projects."/opt/aw-workspace"]\n'
    'trust_level = "trusted"\n'
)

#: What agents-platform-multitenant's executor.py::_build_runner_extra_headers
#: ships over the wire on every single dispatch — the stable X-Aw-Warm-Token
#: alongside the per-turn X-Aw-Caller-Run-Id and (when this run has a card)
#: X-Aw-Context-Notion-Task-Id.
SERVERS_WITH_CONTEXT = {
    "aw-gateway": {
        "type": "streamable-http",
        "url": "http://aw-app-mcp-gateway:9200/mcp",
        "headers": {
            "Authorization": "Bearer live-gateway-token",
            "X-Aw-Caller-Run-Id": "run-turn-1",
            "X-Aw-Warm-Token": "warm-token-abc123",
            "X-Aw-Context-Notion-Task-Id": "task-from-turn-1",
        },
    }
}


# ---------------------------------------------------------------------------
# _strip_stale_identity_headers — the shared helper both CLIs now route through
# ---------------------------------------------------------------------------

def test_strips_any_context_header_but_keeps_caller_run_id_and_warm_token():
    """X-Aw-Warm-Token is deliberately NOT stripped by the shared helper —
    it's the stable key the gateway's Redis fallback is resolved BY, so
    claude (no env-var indirection like codex's) needs it left in place.
    X-Aw-Caller-Run-Id is ALSO kept now (see module docstring): this
    deployment's gateway only ever uses it as a fallback when Redis
    resolution fails, so dropping it removes a safety net for no benefit."""
    headers = execute_mod._strip_stale_identity_headers({
        "Authorization": "Bearer x",
        "X-Aw-Caller-Run-Id": "run-1",
        "X-Aw-Warm-Token": "tok",
        "X-Aw-Context-Notion-Task-Id": "task-1",
        "X-Aw-Context-Source-Device": "telegram",
    })

    assert headers == {
        "Authorization": "Bearer x",
        "X-Aw-Caller-Run-Id": "run-1",
        "X-Aw-Warm-Token": "tok",
    }


def test_none_and_empty_are_safe():
    assert execute_mod._strip_stale_identity_headers(None) == {}
    assert execute_mod._strip_stale_identity_headers({}) == {}


# ---------------------------------------------------------------------------
# codex's _render_codex_config_toml — same fix, closes the X-Aw-Context-*
# gap the old literal-name-only filter missed
# ---------------------------------------------------------------------------

def test_codex_config_toml_also_drops_context_headers():
    cfg = tomllib.loads(
        execute_mod._render_codex_config_toml(SHARED_CODEX_CONFIG_TOML, SERVERS_WITH_CONTEXT))
    server = cfg["mcp_servers"]["aw-gateway"]

    # Authorization rides in via bearer_token_env_var, not a static
    # http_headers value — see _render_codex_config_toml's own docstring
    # and CODEX_GATEWAY_TOKEN_ENV_VAR.
    assert server["bearer_token_env_var"] == execute_mod.CODEX_GATEWAY_TOKEN_ENV_VAR
    assert "http_headers" not in server or "Authorization" not in server["http_headers"]
    # X-Aw-Caller-Run-Id is kept now (see module docstring) — only the
    # unresolvable X-Aw-Context-* family and the env-var-indirected
    # X-Aw-Warm-Token are dropped from the static http_headers table.
    assert server["http_headers"]["X-Aw-Caller-Run-Id"] == "run-turn-1"
    assert "X-Aw-Warm-Token" not in server.get("http_headers", {})
    assert "X-Aw-Context-Notion-Task-Id" not in server.get("http_headers", {})
    assert "task-from-turn-1" not in execute_mod._render_codex_config_toml(
        SHARED_CODEX_CONFIG_TOML, SERVERS_WITH_CONTEXT)


# ---------------------------------------------------------------------------
# claude's mcp.json, via _build_container_kwargs — the actual Gap 2 fix
# ---------------------------------------------------------------------------

BASE_JOB = {
    "run_id": "run-turn-1", "cli": "claude", "agent_id": "agent-1", "prompt": "hi",
    "mcp_servers": SERVERS_WITH_CONTEXT,
}


def _write_claude_mcp_json(tmp_path, monkeypatch) -> dict:
    home = tmp_path / "home"  # deliberately empty — no .claude dir, so
    home.mkdir()               # direct_home_mount stays False and the mcp.json
    monkeypatch.setattr(execute_mod, "REAL_HOME", str(home))
    monkeypatch.setattr(execute_mod, "WORKSPACE_HOME_HOST_DIR", "")
    monkeypatch.setattr(execute_mod, "WORKSPACE_HOST_DIR", "/host/aw-workspace")
    monkeypatch.setattr(execute_mod, "WORKSPACE_CONTAINER_DIR", str(tmp_path / "ws"))

    execute_mod._build_container_kwargs(BASE_JOB)

    mcp_path = tmp_path / "ws" / ".claude" / "isolated" / "run-turn-1" / "mcp.json"
    return json.loads(mcp_path.read_text())


def test_claude_mcp_json_keeps_caller_run_id_and_drops_context_headers(tmp_path, monkeypatch):
    """X-Aw-Caller-Run-Id survives now (see module docstring): this
    deployment's gateway only ever falls back to it when its Redis-backed
    warm-token resolution fails, so dropping it would leave a warm container
    with no caller identity at all whenever Redis isn't configured.
    X-Aw-Context-* still goes — aw-mcp-gateway never forwards or resolves it."""
    doc = _write_claude_mcp_json(tmp_path, monkeypatch)
    headers = doc["mcpServers"]["aw-gateway"]["headers"]

    assert headers["Authorization"] == "Bearer live-gateway-token"
    assert headers["X-Aw-Caller-Run-Id"] == "run-turn-1"
    assert "X-Aw-Context-Notion-Task-Id" not in headers


def test_claude_mcp_json_keeps_the_stable_warm_token(tmp_path, monkeypatch):
    """X-Aw-Warm-Token must survive — it's what lets the gateway's Redis
    fallback (_resolve_warm_token) identify this container's CURRENT turn,
    overriding the (now also-present) frozen X-Aw-Caller-Run-Id when it can."""
    doc = _write_claude_mcp_json(tmp_path, monkeypatch)
    headers = doc["mcpServers"]["aw-gateway"]["headers"]

    assert headers["X-Aw-Warm-Token"] == "warm-token-abc123"
